/**
 * Typed API client for the hosted browser control-plane contract.
 *
 * The schema types are generated by `scripts/gen-hosted-contract` from
 * `apps/control-plane` FastAPI OpenAPI into `./generated/hosted-schema`.
 * Hosted frontend code should use this client instead of handwritten
 * response interfaces in `cloud.ts`.
 */
import createClient, { type Middleware } from "openapi-fetch";
import { dirtApiBaseUrl } from "./client";
import type { paths } from "./generated/hosted-schema";

type HostedApiClient = ReturnType<typeof createClient<paths>>;

interface HostedApiClientOptions {
  baseUrl?: string;
  onUnauthorized?: () => void;
}

const defaultOnUnauthorized = (): void => {
  if (typeof window !== "undefined" && window.location.pathname !== "/login") {
    window.location.assign("/login");
  }
};

class HostedApiError extends Error {
  readonly status: number;

  constructor(method: string, path: string, status: number) {
    super(`${method} ${path} failed with ${status}`);
    this.name = "HostedApiError";
    this.status = status;
  }
}

export const createHostedApiClient = (
  options: HostedApiClientOptions = {},
): HostedApiClient => {
  const { baseUrl = dirtApiBaseUrl, onUnauthorized = defaultOnUnauthorized } = options;

  const client = createClient<paths>({
    baseUrl,
    credentials: "include",
  });

  const unauthorizedMiddleware: Middleware = {
    onResponse: ({ request, response, schemaPath }) => {
      if (response.status === 401) {
        onUnauthorized();
      }
      if (!response.ok) {
        throw new HostedApiError(request.method, schemaPath, response.status);
      }
    },
  };
  client.use(unauthorizedMiddleware);

  return client;
};
