# generated by datamodel-codegen:
#   filename:  webapp-v1.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str


class BandStatus(StrEnum):
    ok = "ok"
    warn = "warn"
    crit = "crit"


class Stage(StrEnum):
    veg = "veg"
    flower_early = "flower_early"
    flower_late = "flower_late"


class Range(StrEnum):
    field_1h = "1h"
    field_24h = "24h"
    field_7d = "7d"


class SensorMetric(StrEnum):
    temperature_f = "temperature_f"
    humidity_pct = "humidity_pct"
    vpd_kpa = "vpd_kpa"
    dew_point_f = "dew_point_f"
    pressure_hpa = "pressure_hpa"
    fan_pct = "fan_pct"
    reservoir_in = "reservoir_in"


class PlantCode(StrEnum):
    """
    Stable lowercase letter; URL path param.
    """

    a = "a"
    b = "b"
    c = "c"
    d = "d"


class PlantStatus(StrEnum):
    primary = "primary"
    secondary = "secondary"
    retired = "retired"


class PlantStickerColor(StrEnum):
    yellow = "yellow"
    orange = "orange"
    pink = "pink"
    blue = "blue"


class DeviceStatusKind(StrEnum):
    ok = "ok"
    listening = "listening"
    warn = "warn"
    offline = "offline"


class HistoryPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ts: AwareDatetime
    value: float


class LoginRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: constr(min_length=1)
    password: constr(min_length=1)


class User(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: str


class LightsState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    on: bool
    on_local: str = Field(..., examples=["05:00:00"])
    """
    Local-time HH:MM:SS (tent timezone).
    """
    off_local: str = Field(..., examples=["23:00:00"])
    """
    Local-time HH:MM:SS (tent timezone).
    """
    minutes_until_off: float
    """
    Always-positive countdown to next lights-off.
    """
    minutes_until_on: float
    """
    Always-positive countdown to next lights-on.
    """


class GrowCurrent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    germination_date: date_aliased
    flower_start_date: date_aliased | None
    day_number: conint(ge=1)
    """
    today − germination_date + 1
    """
    grow_week_number: conint(ge=1)
    """
    1-indexed since germination_date (week 1 = days 1–7).
    """
    flower_week_number: conint(ge=1) | None
    """
    1-indexed since flower_start_date; null while in veg.
    """
    stage: Stage
    strain: str
    location: str
    plant_count: conint(ge=0)
    lights: LightsState


class TargetBand(RootModel[list[float]]):
    """
    [lo, hi] target band; null if no band defined for this metric/stage.
    """

    root: list[float] = Field(..., max_length=2, min_length=2)
    """
    [lo, hi] target band; null if no band defined for this metric/stage.
    """


class MetricEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: float
    unit: str
    target: TargetBand | None
    status: BandStatus
    ts: AwareDatetime


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    temperature_f: MetricEnvelope
    humidity_pct: MetricEnvelope
    vpd_kpa: MetricEnvelope
    fan_pct: MetricEnvelope
    reservoir_in: MetricEnvelope


class SensorsCurrent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ts: AwareDatetime
    stale: bool
    """
    Sensor-stuck flag (is_sensor_stale()).
    """
    metrics: Metrics


class SensorsHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    range: Range
    metric: SensorMetric
    unit: str
    points: list[HistoryPoint]


class HumidifierState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    on: bool
    since: AwareDatetime
    """
    Timestamp of the last transition.
    """
    duration_s: conint(ge=0)
    """
    Seconds since `since`.
    """
    cycles_24h: conint(ge=0)
    """
    Off→on transitions in the last 24h.
    """
    ts: AwareDatetime


class HumidifierTransition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ts: AwareDatetime
    on: bool


class HumidifierHistory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    range: Range
    points: list[HumidifierTransition]


class Plant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: PlantCode
    name: str
    sticker_color: PlantStickerColor
    status: PlantStatus
    purple: bool
    moisture_pct: float | None
    """
    Latest calibrated soil moisture %; null if no calibration.
    """
    moisture_ts: AwareDatetime | None


class PlantsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    day: conint(ge=1)
    plants: list[Plant]


class PlantMoistureCurrent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    current_pct: float | None
    target: TargetBand | None
    status: BandStatus
    ts: AwareDatetime | None


class TimelineEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    day: conint(ge=1)
    text: str
    highlight: bool


class PlantNote(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    updated: date_aliased


class PlantDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: PlantCode
    name: str
    sticker_color: PlantStickerColor
    status: PlantStatus
    purple: bool
    day: conint(ge=1)
    label: str
    moisture: PlantMoistureCurrent
    timeline: list[TimelineEntry]
    note: PlantNote | None
    wiki_path: str


class PlantMoistureHistory(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: PlantCode
    range: Range
    unit: str
    target: TargetBand | None
    points: list[HistoryPoint]
    irrigation_events_24h: conint(ge=0)


class Kind(StrEnum):
    env_sensor = "env_sensor"
    moisture_node = "moisture_node"
    camera = "camera"
    voice = "voice"
    actuator = "actuator"


class DeviceStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    kind: Kind
    status: DeviceStatusKind
    last_seen: AwareDatetime | None
    note: str | None = None


class DevicesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ts: AwareDatetime
    devices: list[DeviceStatus]


class PTZPreset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    label: str
    description: str
    yaw: float
    """
    Motor-frame degrees (same convention as PTZState.yaw).
    """
    pitch: float
    """
    Motor-frame degrees (same convention as PTZState.pitch).
    """
    zoom: float
    sticker_color: PlantStickerColor | None = None


class PTZState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    connected: bool
    yaw: float
    pitch: float
    zoom: float
    preset: str | None
    """
    Current preset id, or null if not at one (~2° tolerance).
    """
    presets: list[PTZPreset]


class PTZApplied(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: bool
    yaw: float
    pitch: float
    zoom: float
    preset: str | None


class PTZLookRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: confloat(ge=-0.5, le=0.5)
    """
    Normalized horizontal click (frame center = 0).
    """
    y: confloat(ge=-0.5, le=0.5)
    """
    Normalized vertical click (frame center = 0).
    """


class PTZZoomRequest(BaseModel):
    """
    Provide exactly one of `zoom` (absolute) or `delta` (relative).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    zoom: confloat(ge=1.0, le=4.0) | None = None
    delta: float | None = None


class PTZZoomResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: bool
    zoom: float


class Type(StrEnum):
    file = "file"


class WikiTreeFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["file"]
    name: str
    path: str
    title: str
    sticker_color: PlantStickerColor | None = None


class Type1(StrEnum):
    folder = "folder"


class WikiBacklink(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    title: str


class WikiFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    title: str
    subtitle: str | None = None
    """
    First italic line of body, if present.
    """
    frontmatter: dict[str, Any]
    """
    YAML frontmatter parsed verbatim.
    """
    body_markdown: str
    """
    Raw markdown body; SPA renders with react-markdown.
    """
    backlinks: list[WikiBacklink]


class MatchType(StrEnum):
    title = "title"
    path = "path"
    content = "content"


class WikiSearchResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    title: str
    match_type: MatchType
    snippet: str | None = None


class WikiSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    q: str
    results: list[WikiSearchResult]


class WikiTreeFolder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["folder"]
    name: str
    children: list[WikiTreeNode]


class WikiTreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tree: list[WikiTreeNode]


class WikiTreeNode(RootModel[WikiTreeFile | WikiTreeFolder]):
    root: WikiTreeFile | WikiTreeFolder = Field(..., discriminator="type")


WikiTreeFolder.model_rebuild()
WikiTreeResponse.model_rebuild()
