import type {
  BreedingLogbookBootstrap,
  PlantDetail,
  PlantListResult,
  PlantRow,
  SeedLotListResult,
} from "./breedingLogbookTypes";

export const BREEDING_LOGBOOK_BOOTSTRAP = {
  today: "2026-06-17",
  todayLabel: "06/17/26",
  plantSexes: [
    { key: "unknown", displayName: "Unknown", displayOrder: 10 },
    { key: "male", displayName: "Male", displayOrder: 20 },
    { key: "female", displayName: "Female", displayOrder: 30 },
    { key: "herm", displayName: "Hermaphrodite", displayOrder: 40 },
    { key: "reversed", displayName: "Reversed", displayOrder: 50 },
  ],
  seedLotSexTypes: [
    { key: "feminized", displayName: "Feminized", displayOrder: 10 },
    { key: "regular", displayName: "Regular", displayOrder: 20 },
    { key: "unknown", displayName: "Unknown", displayOrder: 30 },
  ],
  stages: [
    { key: "germinating", displayName: "Germinating", displayOrder: 10 },
    { key: "veg", displayName: "Veg", displayOrder: 20 },
    { key: "flower", displayName: "Flower", displayOrder: 30 },
    { key: "breeding", displayName: "Breeding", displayOrder: 40 },
    { key: "harvested", displayName: "Harvested", displayOrder: 50 },
    { key: "culled", displayName: "Culled", displayOrder: 60 },
  ],
  locations: [
    { key: "clone", displayName: "Clone / germ", stageKey: "germinating" },
    { key: "veg", displayName: "Veg tent", stageKey: "veg" },
    { key: "main", displayName: "Main flower", stageKey: "flower" },
    { key: "breeding", displayName: "Breeding tent", stageKey: "breeding" },
  ],
} satisfies BreedingLogbookBootstrap;

export const BREEDING_LOGBOOK_SEED_LOTS = {
  seedLots: [
    {
      id: "lot-sbbs-r1-fem",
      label: "SBBS R1 feminized source",
      prefix: "SBBS",
      generation: "R1",
      source: "purchased",
      sourceLabel: "operator archive",
      parentsLabel: "Sugar Black Rose x Black Sugar",
      sexTypeKey: "feminized",
      seedCount: null,
    },
    {
      id: "lot-sbbs-r1-regular",
      label: "SBBS R1 regular males",
      prefix: "R",
      generation: "R1",
      source: "cross",
      sourceLabel: "in-house selection",
      parentsLabel: "Plant D x R2",
      sexTypeKey: "regular",
      seedCount: 42,
    },
    {
      id: "lot-maruf-black",
      label: "Maruf Black seed run",
      prefix: "MB",
      generation: "F2",
      source: "purchased",
      sourceLabel: "Maruf line",
      parentsLabel: "Maruf Black open pollination",
      sexTypeKey: "regular",
      seedCount: 10,
    },
  ],
} satisfies SeedLotListResult;

export const BREEDING_LOGBOOK_PLANTS = {
  activeCount: 9,
  culledCount: 2,
  plants: [
    {
      id: "plant-a",
      key: "SBBS-R1-001",
      name: "Plant A",
      generation: "R1",
      parentsLabel: "Sugar Black Rose x Black Sugar",
      sexKey: "female",
      stageKey: "flower",
      stageDay: 44,
      germinatedOn: "2026-03-17",
      vegStartedOn: "2026-04-02",
      flowerStartedOn: "2026-05-04",
      culledOn: null,
      locationKey: "main",
      locationLabel: "Main flower / A1",
      seedLotLabel: "SBBS R1 feminized source",
      lastNote: "Leaf curl watch at upper canopy edge.",
      telemetrySummary: "4 plant streams",
    },
    {
      id: "plant-b",
      key: "SBBS-R1-002",
      name: "Plant B",
      generation: "R1",
      parentsLabel: "Sugar Black Rose x Black Sugar",
      sexKey: "female",
      stageKey: "flower",
      stageDay: 44,
      germinatedOn: "2026-03-17",
      vegStartedOn: "2026-04-02",
      flowerStartedOn: "2026-05-04",
      culledOn: null,
      locationKey: "main",
      locationLabel: "Main flower / B1",
      seedLotLabel: "SBBS R1 feminized source",
      lastNote: "Canopy photo only; no trusted plant probe.",
      telemetrySummary: "tent context",
    },
    {
      id: "plant-c",
      key: "SBBS-R1-003",
      name: "Plant C",
      generation: "R1",
      parentsLabel: "Sugar Black Rose x Black Sugar",
      sexKey: "female",
      stageKey: "flower",
      stageDay: 44,
      germinatedOn: "2026-03-17",
      vegStartedOn: "2026-04-02",
      flowerStartedOn: "2026-05-04",
      culledOn: null,
      locationKey: "main",
      locationLabel: "Main flower / C1",
      seedLotLabel: "SBBS R1 feminized source",
      lastNote: "Strong branch set; watch lower-site airflow.",
      telemetrySummary: "tent context",
    },
    {
      id: "plant-d",
      key: "SBBS-R1-004",
      name: "Plant D",
      generation: "R1",
      parentsLabel: "Sugar Black Rose x Black Sugar",
      sexKey: "female",
      stageKey: "flower",
      stageDay: 44,
      germinatedOn: "2026-03-17",
      vegStartedOn: "2026-04-02",
      flowerStartedOn: "2026-05-04",
      culledOn: null,
      locationKey: "main",
      locationLabel: "Main flower / D1",
      seedLotLabel: "SBBS R1 feminized source",
      lastNote: "Clone preservation candidate.",
      telemetrySummary: "2 plant streams",
    },
    {
      id: "r1",
      key: "SBBS-R1-005",
      name: "R1",
      generation: "R1",
      parentsLabel: "Plant D x R2",
      sexKey: "male",
      stageKey: "breeding",
      stageDay: 24,
      germinatedOn: "2026-05-01",
      vegStartedOn: "2026-05-14",
      flowerStartedOn: "2026-05-27",
      culledOn: null,
      locationKey: "breeding",
      locationLabel: "Breeding tent / A1",
      seedLotLabel: "SBBS R1 regular males",
      lastNote: "Pollen isolation bag installed.",
      telemetrySummary: "tent context",
    },
    {
      id: "r2",
      key: "SBBS-R1-006",
      name: "R2",
      generation: "R1",
      parentsLabel: "Plant D x R2",
      sexKey: "male",
      stageKey: "breeding",
      stageDay: 24,
      germinatedOn: "2026-05-01",
      vegStartedOn: "2026-05-14",
      flowerStartedOn: "2026-05-27",
      culledOn: null,
      locationKey: "breeding",
      locationLabel: "Breeding tent / B1",
      seedLotLabel: "SBBS R1 regular males",
      lastNote: "Purple pollen sacs photographed.",
      telemetrySummary: "tent context",
    },
    {
      id: "r3",
      key: "SBBS-R1-007",
      name: "R3",
      generation: "R1",
      parentsLabel: "Plant D x R2",
      sexKey: "male",
      stageKey: "breeding",
      stageDay: 24,
      germinatedOn: "2026-05-01",
      vegStartedOn: "2026-05-14",
      flowerStartedOn: "2026-05-27",
      culledOn: null,
      locationKey: "breeding",
      locationLabel: "Breeding tent / C1",
      seedLotLabel: "SBBS R1 regular males",
      lastNote: "Male structure retained for comparison.",
      telemetrySummary: "tent context",
    },
    {
      id: "mb-001",
      key: "MB-R1-001",
      name: "Maruf 001",
      generation: "F2",
      parentsLabel: "Maruf Black open pollination",
      sexKey: "unknown",
      stageKey: "germinating",
      stageDay: 1,
      germinatedOn: "2026-06-17",
      vegStartedOn: null,
      flowerStartedOn: null,
      culledOn: null,
      locationKey: "clone",
      locationLabel: "Clone / germ tray 1",
      seedLotLabel: "Maruf Black seed run",
      lastNote: "Started today.",
      telemetrySummary: "tent context",
    },
    {
      id: "ad-clone-01",
      key: "AD-C1-001",
      name: "A/D clone 001",
      generation: "clone",
      parentsLabel: "Plant A cutting",
      sexKey: "female",
      stageKey: "veg",
      stageDay: 7,
      germinatedOn: "2026-06-10",
      vegStartedOn: "2026-06-10",
      flowerStartedOn: null,
      culledOn: null,
      locationKey: "veg",
      locationLabel: "Veg tent / tray 2",
      seedLotLabel: "A/D clone preservation",
      lastNote: "Rooting watch; dome cracked open.",
      telemetrySummary: "clone context",
    },
    {
      id: "r4",
      key: "SBBS-R1-008",
      name: "R4",
      generation: "R1",
      parentsLabel: "Plant D x R2",
      sexKey: "male",
      stageKey: "culled",
      stageDay: 0,
      germinatedOn: "2026-05-01",
      vegStartedOn: "2026-05-14",
      flowerStartedOn: "2026-05-27",
      culledOn: "2026-06-12",
      locationKey: "removed",
      locationLabel: "Removed",
      seedLotLabel: "SBBS R1 regular males",
      lastNote: "Culled after weak branch structure.",
      telemetrySummary: "archived",
    },
    {
      id: "r5",
      key: "SBBS-R1-009",
      name: "R5",
      generation: "R1",
      parentsLabel: "Plant D x R2",
      sexKey: "male",
      stageKey: "culled",
      stageDay: 0,
      germinatedOn: "2026-05-01",
      vegStartedOn: "2026-05-14",
      flowerStartedOn: "2026-05-27",
      culledOn: "2026-06-13",
      locationKey: "removed",
      locationLabel: "Removed",
      seedLotLabel: "SBBS R1 regular males",
      lastNote: "Culled after low vigor.",
      telemetrySummary: "archived",
    },
  ],
} satisfies PlantListResult;

function requireMockPlant(id: string): PlantRow {
  const plant = BREEDING_LOGBOOK_PLANTS.plants.find((candidate) => candidate.id === id);
  if (!plant) {
    throw new Error(`Missing Breeding Logbook mock plant ${id}`);
  }
  return plant;
}

const selectedPlant = requireMockPlant("plant-a");

export const BREEDING_LOGBOOK_SELECTED_PLANT_DETAIL = {
  plant: selectedPlant,
  lineage: {
    parents: selectedPlant.parentsLabel,
    offspring: "A/D clone preservation · 8 cuttings",
  },
  metrics: [
    { label: "Substrate moisture", value: "31%", tone: "warn" },
    { label: "Substrate EC", value: "1.42", tone: "ok" },
    { label: "Air temp", value: "25.1C", tone: "ok" },
  ],
  metricHistory: [
    {
      key: "moisture",
      label: "Substrate moisture",
      value: "31",
      unit: "%",
      tone: "warn",
      points: [28, 31, 33, 30, 29, 31],
    },
    {
      key: "ec",
      label: "Substrate EC",
      value: "1.42",
      unit: "mS",
      tone: "ok",
      points: [1.2, 1.34, 1.28, 1.4, 1.38, 1.42],
    },
    {
      key: "ph",
      label: "pH",
      value: "5.9",
      unit: "",
      tone: "ok",
      points: [6.1, 5.9, 5.8, 5.8, 5.9, 5.9],
    },
    {
      key: "temperature",
      label: "Air temp",
      value: "25.1",
      unit: "C",
      tone: "ok",
      points: [24.8, 25.2, 25.0, 25.4, 25.1, 25.1],
    },
  ],
  events: [
    {
      id: "evt-note-leaf-curl",
      dateLabel: "Jun 17",
      tag: "note",
      body: "Leaves curling at upper canopy edge.",
      hasPhoto: false,
    },
    {
      id: "evt-photo-upper-canopy",
      dateLabel: "Jun 14",
      tag: "note",
      body: "Upper canopy photo attached for comparison.",
      hasPhoto: true,
    },
    {
      id: "evt-flower",
      dateLabel: "May 04",
      tag: "stage",
      body: "Moved into flower cycle.",
      hasPhoto: false,
    },
    {
      id: "evt-germ",
      dateLabel: "Mar 17",
      tag: "germ",
      body: "Seedling recorded from SBBS R1 feminized source.",
      hasPhoto: false,
    },
  ],
} satisfies PlantDetail;
