/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BreedingLogbookRouteImport } from './routes/breeding-logbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TentsTentIdPlantsPlantIdRouteImport } from './routes/tents.$tentId.plants.$plantId'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedingLogbookRoute = BreedingLogbookRouteImport.update({
  id: '/breeding-logbook',
  path: '/breeding-logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TentsTentIdPlantsPlantIdRoute =
  TentsTentIdPlantsPlantIdRouteImport.update({
    id: '/tents/$tentId/plants/$plantId',
    path: '/tents/$tentId/plants/$plantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breeding-logbook': typeof BreedingLogbookRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/wiki': typeof WikiRoute
  '/tents/$tentId/plants/$plantId': typeof TentsTentIdPlantsPlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breeding-logbook': typeof BreedingLogbookRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/wiki': typeof WikiRoute
  '/tents/$tentId/plants/$plantId': typeof TentsTentIdPlantsPlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breeding-logbook': typeof BreedingLogbookRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/wiki': typeof WikiRoute
  '/tents/$tentId/plants/$plantId': typeof TentsTentIdPlantsPlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breeding-logbook'
    | '/live'
    | '/login'
    | '/wiki'
    | '/tents/$tentId/plants/$plantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breeding-logbook'
    | '/live'
    | '/login'
    | '/wiki'
    | '/tents/$tentId/plants/$plantId'
  id:
    | '__root__'
    | '/'
    | '/breeding-logbook'
    | '/live'
    | '/login'
    | '/wiki'
    | '/tents/$tentId/plants/$plantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreedingLogbookRoute: typeof BreedingLogbookRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  WikiRoute: typeof WikiRoute
  TentsTentIdPlantsPlantIdRoute: typeof TentsTentIdPlantsPlantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeding-logbook': {
      id: '/breeding-logbook'
      path: '/breeding-logbook'
      fullPath: '/breeding-logbook'
      preLoaderRoute: typeof BreedingLogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tents/$tentId/plants/$plantId': {
      id: '/tents/$tentId/plants/$plantId'
      path: '/tents/$tentId/plants/$plantId'
      fullPath: '/tents/$tentId/plants/$plantId'
      preLoaderRoute: typeof TentsTentIdPlantsPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreedingLogbookRoute: BreedingLogbookRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  WikiRoute: WikiRoute,
  TentsTentIdPlantsPlantIdRoute: TentsTentIdPlantsPlantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
