// MSW v2 request handlers.
//
// Each FE feature appends its own `http.{get,post,...}` handler to this
// array. See docs/references/msw-v2/handlers.md for the v2 resolver
// signature — `http.get("/api/x", ({ request, params, cookies }) =>
// HttpResponse.json(...))`, NOT the v1 `rest.get(..., (req, res, ctx) =>
// res(ctx.json(...)))` shape.
//
// This array is shared between browser-mode (dev via Service Worker)
// and node-mode (Vitest via setupServer). Keep handlers relative /
// same-origin where possible; prod serves the real endpoints on the
// same origin and MSW is tree-shaken out of the prod bundle.
import { HttpResponse, http, type RequestHandler } from "msw";

// Captured-from-live-BE fixtures. Generated by scripts/capture-fixtures
// hitting http://127.0.0.1:8001 with an admin session. Refresh by
// re-running the script; the JSON diff is the contract-drift signal.
// Endpoints still using inline fixture data (auth login/logout, feed,
// ptz mutations, wiki tree/file/search) have drift behavior that isn't
// reducible to a flat capture — see docs/plans/contract-drift-report.md.
import authMe from "./fixtures/auth.me.json";
import growCurrent from "./fixtures/grow.current.json";
import plantA from "./fixtures/plants.a.json";
import plantAMoisture1h from "./fixtures/plants.a.moisture.1h.json";
import plantAMoisture7d from "./fixtures/plants.a.moisture.7d.json";
import plantAMoisture24h from "./fixtures/plants.a.moisture.24h.json";
import plantB from "./fixtures/plants.b.json";
import plantBMoisture1h from "./fixtures/plants.b.moisture.1h.json";
import plantBMoisture7d from "./fixtures/plants.b.moisture.7d.json";
import plantBMoisture24h from "./fixtures/plants.b.moisture.24h.json";
import plantC from "./fixtures/plants.c.json";
import plantCMoisture1h from "./fixtures/plants.c.moisture.1h.json";
import plantCMoisture7d from "./fixtures/plants.c.moisture.7d.json";
import plantCMoisture24h from "./fixtures/plants.c.moisture.24h.json";
import plantD from "./fixtures/plants.d.json";
import plantDMoisture1h from "./fixtures/plants.d.moisture.1h.json";
import plantDMoisture7d from "./fixtures/plants.d.moisture.7d.json";
import plantDMoisture24h from "./fixtures/plants.d.moisture.24h.json";
import plantsList from "./fixtures/plants.json";
import ptzStateInitial from "./fixtures/ptz.state.json";
import sensorsCurrent from "./fixtures/sensors.current.json";
import sensorsHistory1hFanPct from "./fixtures/sensors.history.1h.fan_pct.json";
import sensorsHistory1hHumidifierIntensityPct from "./fixtures/sensors.history.1h.humidifier_intensity_pct.json";
import sensorsHistory1hHumidityPct from "./fixtures/sensors.history.1h.humidity_pct.json";
import sensorsHistory1hReservoirIn from "./fixtures/sensors.history.1h.reservoir_in.json";
import sensorsHistory1hTemperatureF from "./fixtures/sensors.history.1h.temperature_f.json";
import sensorsHistory1hVpdKpa from "./fixtures/sensors.history.1h.vpd_kpa.json";
import sensorsHistory7dFanPct from "./fixtures/sensors.history.7d.fan_pct.json";
import sensorsHistory7dHumidifierIntensityPct from "./fixtures/sensors.history.7d.humidifier_intensity_pct.json";
import sensorsHistory7dHumidityPct from "./fixtures/sensors.history.7d.humidity_pct.json";
import sensorsHistory7dReservoirIn from "./fixtures/sensors.history.7d.reservoir_in.json";
import sensorsHistory7dTemperatureF from "./fixtures/sensors.history.7d.temperature_f.json";
import sensorsHistory7dVpdKpa from "./fixtures/sensors.history.7d.vpd_kpa.json";
import sensorsHistory24hFanPct from "./fixtures/sensors.history.24h.fan_pct.json";
import sensorsHistory24hHumidifierIntensityPct from "./fixtures/sensors.history.24h.humidifier_intensity_pct.json";
import sensorsHistory24hHumidityPct from "./fixtures/sensors.history.24h.humidity_pct.json";
import sensorsHistory24hReservoirIn from "./fixtures/sensors.history.24h.reservoir_in.json";
import sensorsHistory24hTemperatureF from "./fixtures/sensors.history.24h.temperature_f.json";
import sensorsHistory24hVpdKpa from "./fixtures/sensors.history.24h.vpd_kpa.json";
import sensorsMetadata from "./fixtures/sensors.metadata.json";
import systemDevices from "./fixtures/system.devices.json";

// ---------------------------------------------------------------------------
// frontend.login — /api/auth/{login,logout,me} fixture.
//
// The real backend feature (backend.auth) lands in parallel; until it
// merges, dev + tests rely on these handlers so the FE /login screen can
// be exercised end-to-end. In prod MSW is tree-shaken and these handlers
// never execute.
//
// Schema shapes below are inlined duck-typed mirrors of
// contracts/webapp-v1.yaml #/components/schemas/{LoginRequest,User,ErrorDetail}.
// The boundaries lint rule forbids mocks/ → api-client/, even for
// `import type`, so we can't reference the generated schema types
// directly. If the contract ever drifts, `pnpm typecheck` against the
// real endpoint consumers (routes/login.tsx etc.) surfaces the
// mismatch; the fixture staying locally typed keeps the mock surface
// cleanly separated from domain code.
//
// Session state is a module-level boolean: MSW's Service Worker can
// emit a `Set-Cookie: dirt_session=mock` header (handy for humans
// eyeballing devtools and for the acceptance-script cookie assertion),
// but the browser won't round-trip that cookie back into subsequent
// fetch requests because our real backend will issue it httponly and
// the SW can't set httponly cookies itself. An in-memory flag is the
// simplest fixture that keeps /api/auth/me's 200-after-login behaviour
// correct for both contexts (browser + Vitest node).
//
// Credentials baked into the fixture (planner contract for login.sh):
//   admin / changeme → 200 + User
//   everything else   → 401 + ErrorDetail
// ---------------------------------------------------------------------------

interface LoginRequestBody {
  username: string;
  password: string;
}
interface ErrorDetail {
  detail: string;
}

let isAuthed = false;

export const handlers: RequestHandler[] = [
  http.post("/api/auth/login", async ({ request }) => {
    const body = (await request.json()) as Partial<LoginRequestBody>;
    if (body?.username === "admin" && body?.password === "changeme") {
      isAuthed = true;
      return HttpResponse.json(authMe, {
        headers: { "Set-Cookie": "dirt_session=mock; Path=/" },
      });
    }
    const err: ErrorDetail = { detail: "invalid_credentials" };
    return HttpResponse.json(err, { status: 401 });
  }),

  http.post("/api/auth/logout", () => {
    isAuthed = false;
    return new HttpResponse(null, {
      status: 204,
      headers: {
        "Set-Cookie": "dirt_session=; Path=/; Max-Age=0",
      },
    });
  }),

  http.get("/api/auth/me", () => {
    if (isAuthed) return HttpResponse.json(authMe);
    const err: ErrorDetail = { detail: "unauthorized" };
    return HttpResponse.json(err, { status: 401 });
  }),

  // -------------------------------------------------------------------------
  // frontend.dashboard.gauges — /api/sensors/current + /api/grow/current
  //
  // Fixtures for the five-gauge dashboard. Shapes duck-typed against
  // contracts/webapp-v1.yaml #/components/schemas/{SensorsCurrent,GrowCurrent}
  // (boundaries forbids mocks/ → api-client/, so no `import type` from
  // generated schema — any drift gets caught by route/component typecheck
  // against the real api-client types, not here).
  //
  // Values chosen to land inside the veg-stage STAGE_TARGETS bands (see
  // apps/shared/src/dirt_shared/services/grow_state.py) so band_status =
  // "ok" for every metric. The e2e spec's status-color assertion counts
  // on that: five "ok" tiles → one deterministic status badge to match.
  //
  // Bands per metric:
  //   temperature_f: (70, 82)    → 76 is mid-band
  //   humidity_pct:  (45, 55)    → 50 is mid-band
  //   vpd_kpa:       (0.8, 1.2)  → 1.0 is mid-band
  //   fan_pct, reservoir_in: no band (null target) — gauge renders without
  //   an arc, status is "ok" by band_status(value, null) convention.
  // -------------------------------------------------------------------------

  http.get("/api/sensors/current", () => HttpResponse.json(sensorsCurrent)),

  // -------------------------------------------------------------------------
  // frontend.dashboard.sparklines — /api/sensors/history
  //
  // Fixture for the five-sparkline strip. Shape duck-typed against
  // contracts/webapp-v1.yaml #/components/schemas/SensorsHistoryResponse
  // (boundaries forbids mocks/ → api-client/, so no `import type` from
  // generated schema — any drift gets caught by consumer typecheck).
  //
  // Contract:
  //   range ∈ {"1h","24h","7d"}, metric ∈ {"temperature_f","humidity_pct",
  //     "vpd_kpa","fan_pct","reservoir_in"}.
  //   points[] length depends on range so the e2e can observe bucket
  //   count changes per range (1h → 12, 24h → 48, 7d → 168).
  //   Values are deterministic per (range, metric) — a triangle wave
  //   with per-metric amplitude around a per-metric baseline. Same
  //   (range, metric) pair → identical series across fetches, so the
  //   crosshair/tooltip assertions are stable.
  //   unit mirrors the /api/sensors/current envelope per metric.
  // -------------------------------------------------------------------------

  http.get("/api/sensors/history", ({ request }) => {
    const url = new URL(request.url);
    const range = url.searchParams.get("range");
    const metric = url.searchParams.get("metric");

    const FIXTURES: Record<string, Record<string, unknown>> = {
      "1h:temperature_f": sensorsHistory1hTemperatureF,
      "1h:humidity_pct": sensorsHistory1hHumidityPct,
      "1h:vpd_kpa": sensorsHistory1hVpdKpa,
      "1h:fan_pct": sensorsHistory1hFanPct,
      "1h:humidifier_intensity_pct": sensorsHistory1hHumidifierIntensityPct,
      "1h:reservoir_in": sensorsHistory1hReservoirIn,
      "24h:temperature_f": sensorsHistory24hTemperatureF,
      "24h:humidity_pct": sensorsHistory24hHumidityPct,
      "24h:vpd_kpa": sensorsHistory24hVpdKpa,
      "24h:fan_pct": sensorsHistory24hFanPct,
      "24h:humidifier_intensity_pct": sensorsHistory24hHumidifierIntensityPct,
      "24h:reservoir_in": sensorsHistory24hReservoirIn,
      "7d:temperature_f": sensorsHistory7dTemperatureF,
      "7d:humidity_pct": sensorsHistory7dHumidityPct,
      "7d:vpd_kpa": sensorsHistory7dVpdKpa,
      "7d:fan_pct": sensorsHistory7dFanPct,
      "7d:humidifier_intensity_pct": sensorsHistory7dHumidifierIntensityPct,
      "7d:reservoir_in": sensorsHistory7dReservoirIn,
    };
    if (!range || !["1h", "24h", "7d"].includes(range)) {
      return HttpResponse.json({ detail: "bad_range" }, { status: 400 });
    }
    if (
      !metric ||
      ![
        "temperature_f",
        "humidity_pct",
        "vpd_kpa",
        "fan_pct",
        "humidifier_intensity_pct",
        "reservoir_in",
      ].includes(metric)
    ) {
      return HttpResponse.json({ detail: "bad_metric" }, { status: 400 });
    }
    const fixture = FIXTURES[`${range}:${metric}`];
    return HttpResponse.json(fixture);
  }),

  // -------------------------------------------------------------------------
  // frontend.dashboard.metadata — /api/sensors/metadata
  //
  // Per-metric display metadata (display_name, unit, accent, y-axis
  // bounds, has_target_band). Read once at SPA boot to drive the gauge
  // + sparkline grid. Stable across stage flips — band *values* come
  // from /api/sensors/current per stage; only band *presence* lives here.
  // -------------------------------------------------------------------------

  http.get("/api/sensors/metadata", () => HttpResponse.json(sensorsMetadata)),

  // -------------------------------------------------------------------------
  // frontend.dashboard.plants_strip — /api/plants
  //
  // Fixture for the dashboard plants strip (four A/B/C/D cards). Shape
  // duck-typed against contracts/webapp-v1.yaml
  // #/components/schemas/{PlantsResponse,Plant,PlantStickerColor,PlantStatus}
  // (boundaries forbids mocks/ → api-client/, so no `import type` from
  // generated schema — consumer typecheck catches drift).
  //
  // Sticker colours: one per plant, matching the mockup reference
  // (docs/plans/refs/dashboard.png) — A yellow, B orange, C pink, D blue.
  // `moisture_pct` chosen distinct per plant so the spec can match each
  // card's moisture-bar width to its plant's reading without ambiguity.
  // -------------------------------------------------------------------------

  http.get("/api/plants", () => HttpResponse.json(plantsList)),

  // -------------------------------------------------------------------------
  // frontend.plant_detail — /api/plants/{code} + /api/plants/{code}/moisture
  //
  // Fixtures for the plant-detail drawer (header + moisture hero +
  // timeline + note) and its 24h moisture history chart. Shapes
  // duck-typed against contracts/webapp-v1.yaml
  // #/components/schemas/{PlantDetail,PlantMoistureCurrent,TimelineEntry,
  //                       PlantNote,PlantMoistureHistory}.
  //
  // Per-plant metadata mirrors /api/plants above (sticker A=yellow,
  // B=orange, C=pink, D=blue; moisture 62/48/54/66) so the drawer agrees
  // with the card the user clicked. Timeline + note strings are static
  // per plant — deterministic so the e2e's row-count + header-text
  // assertions are stable across runs.
  // -------------------------------------------------------------------------

  http.get("/api/plants/:code", ({ params }) => {
    const code = String(params.code);
    const BY_CODE: Record<string, Record<string, unknown>> = {
      a: plantA,
      b: plantB,
      c: plantC,
      d: plantD,
    };
    const fixture = BY_CODE[code];
    if (!fixture) {
      return HttpResponse.json({ detail: "not_found" }, { status: 404 });
    }
    return HttpResponse.json(fixture);
  }),

  http.get("/api/plants/:code/moisture", ({ request, params }) => {
    const code = String(params.code);
    const url = new URL(request.url);
    const range = url.searchParams.get("range") ?? "24h";
    const FIXTURES: Record<string, Record<string, Record<string, unknown>>> = {
      a: { "1h": plantAMoisture1h, "24h": plantAMoisture24h, "7d": plantAMoisture7d },
      b: { "1h": plantBMoisture1h, "24h": plantBMoisture24h, "7d": plantBMoisture7d },
      c: { "1h": plantCMoisture1h, "24h": plantCMoisture24h, "7d": plantCMoisture7d },
      d: { "1h": plantDMoisture1h, "24h": plantDMoisture24h, "7d": plantDMoisture7d },
    };
    const byRange = FIXTURES[code];
    if (!byRange) {
      return HttpResponse.json({ detail: "not_found" }, { status: 404 });
    }
    const fixture = byRange[range];
    if (!fixture) {
      return HttpResponse.json({ detail: "bad_range" }, { status: 400 });
    }
    return HttpResponse.json(fixture);
  }),

  // -------------------------------------------------------------------------
  // frontend.dashboard.system_table — /api/system/devices
  //
  // Fixture for the dashboard system table (one row per device). Shape
  // duck-typed against contracts/webapp-v1.yaml
  // #/components/schemas/{DevicesResponse,DeviceStatus,DeviceStatusKind}
  // (boundaries forbids mocks/ → api-client/, so no `import type` from
  // generated schema — consumer typecheck catches drift).
  //
  // Eight devices chosen to cover the full DeviceStatusKind enum
  // (ok|listening|warn|offline) — at least one row per status — so the
  // e2e spec can assert that each row's badge text matches the fixture's
  // status value for that row. Ordering is stable so the spec can pair
  // rows to fixture entries by index.
  // -------------------------------------------------------------------------

  http.get("/api/system/devices", () => HttpResponse.json(systemDevices)),

  // -------------------------------------------------------------------------
  // frontend.live — /api/feed/live.jpg, /api/ptz/{state,preset/{id},look,zoom}
  //
  // Fixtures for the Live tab (camera feed + PTZ controls). Shapes duck-
  // typed against contracts/webapp-v1.yaml
  // #/components/schemas/{PTZState,PTZPreset,PTZApplied,PTZLookRequest,
  //                       PTZZoomRequest,PTZZoomResponse}.
  //
  // /api/feed/live.jpg — returns a tiny 1×1 baseline JPEG so the Live
  //   route's <img src="/api/feed/live.jpg?t=…"> actually loads in dev +
  //   e2e. A real binary JPEG byte-sequence (not a placeholder PNG) so
  //   Content-Type: image/jpeg is truthful. Cache-Control: no-store so
  //   the browser's HTTP cache doesn't hide the ~10s cache-bust refresh.
  //
  // PTZ state: module-level mutable. /api/ptz/state returns the current
  //   position; preset/look/zoom mutate it and echo back PTZApplied /
  //   PTZZoomResponse so the UI's onSuccess → invalidate → refetch sees
  //   the updated values.
  //
  // Preset ids baked in: overview + plant_a..d (matches the mockup
  // reference docs/plans/refs/live.png).
  // -------------------------------------------------------------------------

  // A 1×1 baseline JPEG, produced offline and inlined as bytes. 125 bytes
  // total — the smallest valid JPEG (SOI + APP0 + SOF0 + DQT + DHT × 4 +
  // SOS + EOI is too large, so this uses a minimal grayscale baseline
  // encoder's output). The exact bytes don't matter for the e2e — the
  // spec asserts the <img src> pattern + the network request fires, not
  // image pixel content.
  // biome-ignore format: keep the table columnar for review.
  http.get("/api/feed/live.jpg", () => {
    const bytes = new Uint8Array([
      0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01,
      0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xff, 0xdb, 0x00, 0x43,
      0x00, 0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07, 0x07, 0x07, 0x09,
      0x09, 0x08, 0x0a, 0x0c, 0x14, 0x0d, 0x0c, 0x0b, 0x0b, 0x0c, 0x19, 0x12,
      0x13, 0x0f, 0x14, 0x1d, 0x1a, 0x1f, 0x1e, 0x1d, 0x1a, 0x1c, 0x1c, 0x20,
      0x24, 0x2e, 0x27, 0x20, 0x22, 0x2c, 0x23, 0x1c, 0x1c, 0x28, 0x37, 0x29,
      0x2c, 0x30, 0x31, 0x34, 0x34, 0x34, 0x1f, 0x27, 0x39, 0x3d, 0x38, 0x32,
      0x3c, 0x2e, 0x33, 0x34, 0x32, 0xff, 0xc0, 0x00, 0x0b, 0x08, 0x00, 0x01,
      0x00, 0x01, 0x01, 0x01, 0x11, 0x00, 0xff, 0xc4, 0x00, 0x1f, 0x00, 0x00,
      0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
      0x09, 0x0a, 0x0b, 0xff, 0xc4, 0x00, 0xb5, 0x10, 0x00, 0x02, 0x01, 0x03,
      0x03, 0x02, 0x04, 0x03, 0x05, 0x05, 0x04, 0x04, 0x00, 0x00, 0x01, 0x7d,
      0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21, 0x31, 0x41, 0x06,
      0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xa1, 0x08,
      0x23, 0x42, 0xb1, 0xc1, 0x15, 0x52, 0xd1, 0xf0, 0x24, 0x33, 0x62, 0x72,
      0x82, 0xff, 0xda, 0x00, 0x08, 0x01, 0x01, 0x00, 0x00, 0x3f, 0x00, 0xfb,
      0xd3, 0xff, 0xd9,
    ]);
    return new HttpResponse(bytes, {
      status: 200,
      headers: {
        "Content-Type": "image/jpeg",
        "Cache-Control": "no-store",
      },
    });
  }),

  // Preset table — exactly matches the five rows the Live route renders.
  // `sticker_color` null on overview, non-null per plant (mirrors the
  // contract's optional PTZPreset.sticker_color field).
  ...(() => {
    // Initial PTZ state + preset table imported from the captured
    // ptz.state.json fixture. Mutation handlers keep their behavior —
    // they mutate the module-scoped `state` so subsequent GETs reflect
    // each preset/look/zoom action.
    const PRESETS = ptzStateInitial.presets;

    // Module-scoped mutable position seeded from the capture.
    const state = {
      connected: ptzStateInitial.connected,
      yaw: ptzStateInitial.yaw,
      pitch: ptzStateInitial.pitch,
      zoom: ptzStateInitial.zoom,
      preset: ptzStateInitial.preset as string | null,
    };

    const snapshot = () => ({
      connected: state.connected,
      yaw: state.yaw,
      pitch: state.pitch,
      zoom: state.zoom,
      preset: state.preset,
      presets: PRESETS,
    });

    return [
      http.get("/api/ptz/state", () => HttpResponse.json(snapshot())),

      http.post("/api/ptz/preset/:id", ({ params }) => {
        const id = String(params.id);
        const preset = PRESETS.find((p) => p.id === id);
        if (!preset) {
          return HttpResponse.json({ detail: "preset_not_found" }, { status: 404 });
        }
        state.yaw = preset.yaw;
        state.pitch = preset.pitch;
        state.zoom = preset.zoom;
        state.preset = preset.id;
        return HttpResponse.json({
          ok: true,
          yaw: state.yaw,
          pitch: state.pitch,
          zoom: state.zoom,
          preset: state.preset,
        });
      }),

      http.post("/api/ptz/look", async ({ request }) => {
        const body = (await request.json()) as Partial<{ x: number; y: number }>;
        if (typeof body?.x !== "number" || typeof body?.y !== "number") {
          return HttpResponse.json({ detail: "bad_coords" }, { status: 400 });
        }
        // Naive look → yaw/pitch projection for the fixture. The real
        // service does geometry; the mock just records that a click-to-
        // look fired and nulls the active preset (per PTZApplied.preset
        // = null after manual moves).
        state.yaw += body.x * 10;
        state.pitch += body.y * 10;
        state.preset = null;
        return HttpResponse.json({
          ok: true,
          yaw: state.yaw,
          pitch: state.pitch,
          zoom: state.zoom,
          preset: state.preset,
        });
      }),

      http.post("/api/ptz/zoom", async ({ request }) => {
        const body = (await request.json()) as Partial<{
          zoom?: number;
          delta?: number;
        }>;
        const hasZoom = typeof body?.zoom === "number";
        const hasDelta = typeof body?.delta === "number";
        if (hasZoom === hasDelta) {
          // Contract: exactly one of {zoom, delta} must be provided.
          return HttpResponse.json(
            { detail: "provide_exactly_one_of_zoom_or_delta" },
            { status: 422 },
          );
        }
        if (hasZoom && typeof body.zoom === "number") {
          state.zoom = body.zoom;
        } else if (hasDelta && typeof body.delta === "number") {
          state.zoom += body.delta;
        }
        return HttpResponse.json({ ok: true, zoom: state.zoom });
      }),
    ];
  })(),

  // -------------------------------------------------------------------------
  // frontend.wiki — /api/wiki/{tree,file,search}
  //
  // Fixtures for the Wiki tab (sidebar tree + markdown pane + Cmd+K search
  // palette). Shapes duck-typed against contracts/webapp-v1.yaml
  // #/components/schemas/{WikiTreeResponse,WikiTreeNode,WikiTreeFile,
  //                       WikiTreeFolder,WikiFile,WikiBacklink,
  //                       WikiSearchResponse,WikiSearchResult,PlantStickerColor}
  // (boundaries forbids mocks/ → api-client/, so no `import type` from
  // generated schema — consumer typecheck catches drift).
  //
  // /api/wiki/tree — a realistic three-folder layout:
  //   overview.md + index.md (root files)
  //   plants/ (plant-a..d.md, each with the matching PlantStickerColor)
  //   concepts/ (topping.md, anthocyanin.md, lst.md)
  //   daily/ (one entry per recent grow day)
  // CLAUDE.md is excluded server-side; we mirror that by not emitting it
  // at all. Sorting: root files first (alphabetical), then folders
  // (alphabetical) — same order the backend's `get_tree` produces.
  //
  // /api/wiki/file — a small path → page registry. plant-a.md is the
  // headline page the e2e exercises; it carries a frontmatter block with
  // `type`, `status`, `strain` plus a markdown body that contains a
  // subtitle (first italic line) and more than one heading so the render
  // assertions are non-trivial. Missing paths → 404, traversal → 400.
  //
  // /api/wiki/search — a title/path/content matcher against the same
  // registry. Empty/whitespace q → 400 (mirrors the backend contract).
  // -------------------------------------------------------------------------

  ...(() => {
    // Wiki content registry. One entry per on-disk .md file the fixture
    // exposes. `folder` drives the tree layout; `sticker_color` is only
    // meaningful inside `plants/`. Body is a raw-markdown string whose
    // first paragraph (after the H1) begins with `*…*` when we want a
    // subtitle surfaced on /api/wiki/file.
    interface WikiEntry {
      folder: string | null;
      name: string;
      title: string;
      sticker_color: "yellow" | "orange" | "pink" | "blue" | null;
      frontmatter: Record<string, unknown>;
      subtitle: string | null;
      body: string;
    }

    const PAGES: readonly WikiEntry[] = [
      {
        folder: null,
        name: "index.md",
        title: "Wiki Index",
        sticker_color: null,
        frontmatter: { title: "Wiki Index" },
        subtitle: null,
        body: "# Wiki Index\n\nTop-level pointers into the grow wiki.\n",
      },
      {
        folder: null,
        name: "overview.md",
        title: "Grow Overview",
        sticker_color: null,
        frontmatter: { title: "Grow Overview" },
        subtitle: null,
        body: "# Grow Overview\n\nSirius Black × BS01, four plants in a closet tent.\n",
      },
      {
        folder: "plants",
        name: "plant-a.md",
        title: "Plant A — Purple Keeper Candidate",
        sticker_color: "yellow",
        frontmatter: {
          title: "Plant A — Purple Keeper Candidate",
          type: "plant",
          status: "primary",
          strain: "Sirius Black × BS01",
        },
        subtitle: "Formerly labeled Plant 1.",
        body:
          "# Plant A — Purple Keeper Candidate\n\n" +
          "*Formerly labeled Plant 1.*\n\n" +
          "## Current State\n\n" +
          "Topped on Day 38 (Apr 21); now in recovery. Cut above node 4. " +
          "Most vigorous plant of the four, with D about a day behind. " +
          "Applied topping above node 4 and observed the 5th node emerging " +
          "when we cut.\n\n" +
          "## Notes\n\n" +
          "Day 38 was the right call — plant had visible life node emerging.\n",
      },
      {
        folder: "plants",
        name: "plant-b.md",
        title: "Plant B",
        sticker_color: "orange",
        frontmatter: { title: "Plant B", type: "plant" },
        subtitle: null,
        body: "# Plant B\n\nUpright structure; trailing A by ~a day.\n",
      },
      {
        folder: "plants",
        name: "plant-c.md",
        title: "Plant C",
        sticker_color: "pink",
        frontmatter: { title: "Plant C", type: "plant" },
        subtitle: null,
        body: "# Plant C\n\nPurple stem; likely anthocyanin stress.\n",
      },
      {
        folder: "plants",
        name: "plant-d.md",
        title: "Plant D",
        sticker_color: "blue",
        frontmatter: { title: "Plant D", type: "plant" },
        subtitle: null,
        body: "# Plant D\n\nStandard sibling; mirrors A at ~one day behind.\n",
      },
      {
        folder: "concepts",
        name: "topping.md",
        title: "Topping",
        sticker_color: null,
        frontmatter: { title: "Topping" },
        subtitle: null,
        body:
          "# Topping\n\n" +
          "Prune the apical meristem above a node to force two dominant " +
          "shoots. See [Plant A](../plants/plant-a.md) for a worked example.\n",
      },
      {
        folder: "concepts",
        name: "anthocyanin.md",
        title: "Purple Pigment Biology",
        sticker_color: null,
        frontmatter: { title: "Purple Pigment Biology" },
        subtitle: null,
        body: "# Purple Pigment Biology\n\nCold-stress signal; unrelated body text.\n",
      },
      {
        folder: "concepts",
        name: "lst.md",
        title: "Low-Stress Training",
        sticker_color: null,
        frontmatter: { title: "Low-Stress Training" },
        subtitle: null,
        body: "# Low-Stress Training\n\nBend-and-tie; complements topping.\n",
      },
      {
        folder: "daily",
        name: "2026-04-18.md",
        title: "2026-04-18 · d29",
        sticker_color: null,
        frontmatter: { title: "2026-04-18 · d29" },
        subtitle: null,
        body: "# 2026-04-18 · d29\n\nDaily entry.\n",
      },
      {
        folder: "daily",
        name: "2026-04-17.md",
        title: "2026-04-17 · d28",
        sticker_color: null,
        frontmatter: { title: "2026-04-17 · d28" },
        subtitle: null,
        body: "# 2026-04-17 · d28\n\nDaily entry.\n",
      },
    ];

    const relPath = (e: WikiEntry): string =>
      e.folder === null ? e.name : `${e.folder}/${e.name}`;
    const fullPath = (e: WikiEntry): string => `wiki/${relPath(e)}`;

    const buildTree = () => {
      const rootFiles = PAGES.filter((e) => e.folder === null)
        .slice()
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((e) => ({
          type: "file" as const,
          name: e.name,
          path: fullPath(e),
          title: e.title,
          sticker_color: e.sticker_color,
        }));

      const folderNames = Array.from(
        new Set(PAGES.filter((e) => e.folder !== null).map((e) => e.folder as string)),
      ).sort((a, b) => a.localeCompare(b));

      const folders = folderNames.map((folder) => ({
        type: "folder" as const,
        name: folder,
        children: PAGES.filter((e) => e.folder === folder)
          .slice()
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((e) => ({
            type: "file" as const,
            name: e.name,
            path: fullPath(e),
            title: e.title,
            sticker_color: e.sticker_color,
          })),
      }));

      return [...rootFiles, ...folders];
    };

    // Accept both `foo/bar.md` and `wiki/foo/bar.md` forms (matches the
    // backend's path normalization).
    const lookupEntry = (raw: string): WikiEntry | null => {
      const normalized = raw.startsWith("wiki/") ? raw.slice("wiki/".length) : raw;
      return PAGES.find((e) => relPath(e) === normalized) ?? null;
    };

    // Naive-but-stable backlink derivation: any page whose body contains
    // a markdown link `(…/target.md)` counts as a backlink to the target.
    // Same rule the backend's service uses in spirit; not exhaustive,
    // just enough for the e2e's backlinks-rendered assertion to be
    // verifiable if it ever wants it.
    const backlinksFor = (target: WikiEntry) => {
      const tail = target.name;
      return PAGES.filter((p) => p !== target && p.body.includes(`/${tail})`)).map(
        (p) => ({ path: fullPath(p), title: p.title }),
      );
    };

    const rankSearch = (q: string) => {
      const needle = q.toLowerCase();
      const results: Array<{
        path: string;
        title: string;
        match_type: "title" | "path" | "content";
        snippet: string | null;
        // Lower rank sorts first; ties broken by path for determinism.
        rank: number;
      }> = [];
      for (const page of PAGES) {
        const title = page.title.toLowerCase();
        const path = relPath(page).toLowerCase();
        const body = page.body.toLowerCase();
        if (title.includes(needle)) {
          results.push({
            path: fullPath(page),
            title: page.title,
            match_type: "title",
            snippet: null,
            rank: 0,
          });
        } else if (path.includes(needle)) {
          results.push({
            path: fullPath(page),
            title: page.title,
            match_type: "path",
            snippet: null,
            rank: 1,
          });
        } else if (body.includes(needle)) {
          const idx = body.indexOf(needle);
          const start = Math.max(0, idx - 30);
          const end = Math.min(page.body.length, idx + needle.length + 30);
          results.push({
            path: fullPath(page),
            title: page.title,
            match_type: "content",
            snippet: page.body.slice(start, end).replace(/\s+/g, " ").trim(),
            rank: 2,
          });
        }
      }
      return results
        .sort((a, b) => a.rank - b.rank || a.path.localeCompare(b.path))
        .map(({ rank: _rank, ...rest }) => rest);
    };

    return [
      http.get("/api/wiki/tree", () => HttpResponse.json({ tree: buildTree() })),

      http.get("/api/wiki/file", ({ request }) => {
        const url = new URL(request.url);
        const path = url.searchParams.get("path");
        if (path === null || path.length === 0) {
          return HttpResponse.json({ detail: "missing_path" }, { status: 422 });
        }
        // Reject traversal before any lookup — matches backend 400.
        if (path.includes("..")) {
          return HttpResponse.json({ detail: "path_traversal" }, { status: 400 });
        }
        const entry = lookupEntry(path);
        if (!entry) {
          return HttpResponse.json({ detail: "not_found" }, { status: 404 });
        }
        return HttpResponse.json({
          path: fullPath(entry),
          title: entry.title,
          subtitle: entry.subtitle,
          frontmatter: entry.frontmatter,
          body_markdown: entry.body,
          backlinks: backlinksFor(entry),
        });
      }),

      http.get("/api/wiki/search", ({ request }) => {
        const url = new URL(request.url);
        const q = url.searchParams.get("q");
        if (q === null || q.length === 0) {
          // Backend: FastAPI min_length=1 → 422.
          return HttpResponse.json({ detail: "missing_q" }, { status: 422 });
        }
        if (q.trim().length === 0) {
          // Backend: whitespace-only → 400.
          return HttpResponse.json({ detail: "empty_q" }, { status: 400 });
        }
        return HttpResponse.json({ q, results: rankSearch(q.trim()) });
      }),
    ];
  })(),

  http.get("/api/grow/current", () => HttpResponse.json(growCurrent)),
];
