[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = /dev/ttyUSB0
upload_speed = 115200
monitor_speed = 9600
lib_deps =
    adafruit/DHT sensor library@^1.4
    adafruit/Adafruit Unified Sensor@^1.1
    wifwaf/MH-Z19@^1.5
    bblanchon/ArduinoJson@^7

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17
lib_deps =
    bblanchon/ArduinoJson@^7
